name: CI (Stack)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]
  pull_request_review:
    branches: [master]
    types: [submitted]

# TODO(mihaimaruseac): Full matrix on Linux, linearize/trim on the other
# operating systems
jobs:
  build:
    # TODO(mihaimaruseac): Add support for multiple resolvers
    name: Testing with Stack, on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: 'latest'
    - name: Get location of stack folder
      id: get-stack-location
      run: echo "::set-output name=stack-root::$(stack path --stack-root)"
    - name: Cache (Unix platform)
      uses: actions/cache@v2
      with:
        path: ${{ steps.get-stack-location.outputs.stack-root }}
        key: stack-cache-v2-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('hindent.cabal') }}
        restore-keys: |
          stack-cache-v2-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('stack.yaml') }}
          stack-cache-v2-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}
          stack-cache-v2-${{ runner.os }}
    - name: Install dependencies
      run: |
        stack update
        stack build --system-ghc --only-dependencies --test --bench --no-run-tests --no-run-benchmarks
    - name: Build
      run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    - name: Run tests
      run: stack test
    - name: Run benchmarks
      run: stack bench
    # We don't generate stack documentation as documentation for deps does not get cached
    # name: Generate documentation
    # run: stack haddock
    - name: Generate tarball
      run: stack sdist
