name: CI (Stack)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]
  pull_request_review:
    branches: [master]
    types: [submitted]

# TODO(mihaimaruseac): Full matrix on Linux, linearize/trim on the other
# operating systems
jobs:
  build:
    # TODO(mihaimaruseac): Add support for multiple resolvers
    name: Testing with Stack, on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO(mihaimaruseac): MacOS fails to restore cache, disabling
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: 'latest'
    - name: Cache
      uses: actions/cache@v2
      with:
        # TODO(mihaimaruseac): Merge to one path, after https://github.com/actions/setup-haskell/pull/35
        path: |
          ~/.stack
          C:\Users\runneradmin\AppData\Roaming\stack
        key: stack-cache-v2-${{ runner.os }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('hindent.cabal') }}
        restore-keys: |
          stack-cache-v2-${{ runner.os }}-${{ hashFiles('stack.yaml') }}
          stack-cache-v2-${{ runner.os }}
    - name: Install dependencies
      run: |
        stack update
        stack build --system-ghc --only-dependencies --test --bench --no-run-tests --no-run-benchmarks
    - name: Build
      run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    - name: Run tests
      # TODO(mihaimaruseac): fix tests on windows, currently fail with `NoFenceEnd`
      if: matrix.os != 'windows-latest'
      run: stack test
    - name: Run benchmarks
      run: stack bench
    # We don't generate stack documentation as documentation for deps does not get cached
    # name: Generate documentation
    # run: stack haddock
    - name: Generate tarball
      run: stack sdist
